spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: foo:in.flyspark.kafka.Foo1,bar:in.flyspark.kafka.Bar1
